### ISSUE TITLE
Investigate the best ways to turn an already async api in JS into Elm

### ISSUE THREAD

**Issue by TheSeamau5** [TheSeamau5/elm-storage#2]
Currently, the callback returned by `Task.asyncFunction` is run inside the callback provided by the localforage functions. This seems to work but feels mysterious as nothing is returned by these asyncFunctions....

@evancz maybe you have some good advice on working with JS async APIs.

Example: `getItemAsJson`

``` elm
getItemAsJson : String -> Task String Value
```

This function takes a string and returns a task that produces a Json value. Basically what it does is take a key and return the value associated with that key in local storage.

Currently, this is implemented as:

``` js
var getItemAsJson = function(key){
    return Task.asyncFunction(function(callback){
      localforage.getItem(key).then(function(value){
        callback(Task.succeed(value));
      }).catch(function(err){
        callback(Task.fail("Storage Call: getItemAsJson has failed with key: " + key));
      });
    });
  };
```

This function seems to work but it looks weird. Like, the function parameter to `Task.asyncFunction` is not returning anything... yet it seems to work and pipe the value appropriately... is this an issue?

**Comment by evancz** [comment]
That's how it should look! The whole point is that we want to delay for a while, so there is nothing to return immediately.

The only thing weird to me is that the error type is a `String`, otherwise, this looks fine to me!

**Comment by evancz** [comment]
In a future iteration, the API for wrapping up JS may look more like this:

``` javascript
function getItemAsJson(key) {
    return Task.asyncFunction(function(reportOk, reportErr) {
        localforage.getItem(key).then(function(value) {
            reportOk(value);
        }).catch(function(e) {
            reportErr("Storage Call: getItemAsJson has failed with key: " + key);
        });
    });
}
```

That's for later though!

**Comment by TheSeamau5** [comment]
Cool. Thanks! I was a bit worried about this whole async stuff cuz it looked a bit funky (in JS).

As for the errors... I just did it because I need to investigate the types of errors that `localforage` returns. That part is not well documented by localforage and it's hard to track directly from reading the source code (as you can imagine, that source code is mangled up in solving browser oddities and it has an odd business of using drivers).

I'm still not comfortable to putting this on the package site. It seems to work currently, but it needs more twisted examples for me to feel comfortable.
